# Generated by Django 5.1.6 on 2025-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afrotours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=108)),
                ('tour_duration', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
